name: CI/CD

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go test -v -race ./...
  build:
    needs:
      - lint
      - test
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go build -v ./...
