name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: caioreix/testing-actions/.github/workflows/setup.yml@v1
      - uses: caioreix/testing-actions/.github/workflows/lint.yml@v1
      - uses: caioreix/testing-actions/.github/workflows/test.yml@v1
      - run: go build -o ./bin/bot -v ./cmd...
