name: CI

on:
  pull_request:

jobs:
  setup:
    uses: caioreix/testing-actions/.github/workflows/setup.yml@main
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
  test:
    needs: setup
    uses: caioreix/testing-actions/.github/workflows/test.yml@main
  build:
    needs: 
      - setup
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go build -o ./bin/bot -v ./cmd...
