name: CI

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: tree
      - run: ls ${{ github.workspace }}
      - run: ls
      - name: Add Heroku buildin tags
        run: |
          echo // +heroku goVersion go1.11 >> temp.txt
          echo // +heroku install ./cmd/... ./bin/bot >> temp.txt
          cat ./go.mod >> temp.txt
          rm -r go.mod
          cat temp.txt >> go.mod
          rm -r temp.txt
          ls ${{ github.workspace }}
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go test -v -race ./...
  build:
    needs:
      - setup
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go build -o ./bin/bot -v ./cmd...
