name: CI

on:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: echo ${{ github.ref }}
  setup:
    uses: caioreix/testing-actions/.github/workflows/setup.yml@main
  lint:
    needs: setup
    uses: caioreix/testing-actions/.github/workflows/lint.yml@main
  test:
    needs: setup
    uses: caioreix/testing-actions/.github/workflows/test.yml@main
  build:
    needs: 
      - setup
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go build -o ./bin/bot -v ./cmd...
